# Generated by Django 4.2.4 on 2023-08-16 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_alter_room_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
