# Generated by Django 3.2.19 on 2023-07-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230721_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commentt',
            field=models.TextField(null=True),
        ),
    ]
