# Generated by Django 3.2.19 on 2023-07-24 03:17

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20230721_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='nn', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
