# Generated by Django 3.2.19 on 2023-07-28 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
