# Generated by Django 3.2.19 on 2023-07-31 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20230731_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_post',
        ),
    ]
