# Generated by Django 3.2.19 on 2023-07-24 10:02

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=users.models.upload_to, verbose_name='Image'),
        ),
    ]
