# Generated by Django 3.2.19 on 2023-07-24 10:25

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='image',
        ),
        migrations.AddField(
            model_name='newuser',
            name='avatar',
            field=models.ImageField(default='users/default.jpg', upload_to=users.models.upload_to, verbose_name='Image'),
        ),
    ]
