# Generated by Django 3.2.19 on 2023-07-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230724_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='num_comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newuser',
            name='num_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newuser',
            name='num_post',
            field=models.IntegerField(default=0),
        ),
    ]
