# Generated by Django 3.2.19 on 2023-08-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230731_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='newuser',
            name='country',
            field=models.CharField(default='Viet Nam', max_length=100),
        ),
        migrations.AddField(
            model_name='newuser',
            name='occupation',
            field=models.CharField(default='Student at Danang University Of Science And Technology', max_length=100),
        ),
    ]
