# Generated by Django 4.2.4 on 2023-08-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230801_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='about',
            field=models.TextField(blank=True, default='Nhớ gì như nhớ người yêu?', max_length=500, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
    ]
